/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioThreadIdRouteImport } from './routes/studio.$threadId'
import { Route as StudioBusinessRouteImport } from './routes/studio.business'
import { Route as StudioConversationsRouteImport } from './routes/studio.conversations'
import { Route as StudioFollowupsRouteImport } from './routes/studio.followups'
import { Route as StudioListsRouteImport } from './routes/studio.lists'
import { Route as StudioOffersRouteImport } from './routes/studio.offers'
import { Route as StudioPathRouteImport } from './routes/studio.path'
import { Route as StudioTodosRouteImport } from './routes/studio.todos'
import { Route as StudioBriefIndexRouteImport } from './routes/studio.brief.index'
import { Route as StudioBriefBriefIdRouteImport } from './routes/studio.brief.$briefId'
import { Route as StudioCampaignsIndexRouteImport } from './routes/studio.campaigns.index'
import { Route as StudioCampaignsCampaignIdRouteImport } from './routes/studio.campaigns.$campaignId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioThreadIdRoute = StudioThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => StudioRoute,
} as any)
const StudioBusinessRoute = StudioBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => StudioRoute,
} as any)
const StudioConversationsRoute = StudioConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => StudioRoute,
} as any)
const StudioFollowupsRoute = StudioFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => StudioRoute,
} as any)
const StudioListsRoute = StudioListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => StudioRoute,
} as any)
const StudioOffersRoute = StudioOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPathRoute = StudioPathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => StudioRoute,
} as any)
const StudioTodosRoute = StudioTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => StudioRoute,
} as any)
const StudioBriefIndexRoute = StudioBriefIndexRouteImport.update({
  id: '/brief/',
  path: '/brief/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioBriefBriefIdRoute = StudioBriefBriefIdRouteImport.update({
  id: '/brief/$briefId',
  path: '/brief/$briefId',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCampaignsIndexRoute = StudioCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCampaignsCampaignIdRoute =
  StudioCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => StudioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/studio': typeof StudioRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/studio/$threadId': typeof StudioThreadIdRoute
  '/studio/business': typeof StudioBusinessRoute
  '/studio/conversations': typeof StudioConversationsRoute
  '/studio/followups': typeof StudioFollowupsRoute
  '/studio/lists': typeof StudioListsRoute
  '/studio/offers': typeof StudioOffersRoute
  '/studio/path': typeof StudioPathRoute
  '/studio/todos': typeof StudioTodosRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/brief/$briefId': typeof StudioBriefBriefIdRoute
  '/studio/campaigns/$campaignId': typeof StudioCampaignsCampaignIdRoute
  '/studio/brief/': typeof StudioBriefIndexRoute
  '/studio/campaigns/': typeof StudioCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/studio/$threadId': typeof StudioThreadIdRoute
  '/studio/business': typeof StudioBusinessRoute
  '/studio/conversations': typeof StudioConversationsRoute
  '/studio/followups': typeof StudioFollowupsRoute
  '/studio/lists': typeof StudioListsRoute
  '/studio/offers': typeof StudioOffersRoute
  '/studio/path': typeof StudioPathRoute
  '/studio/todos': typeof StudioTodosRoute
  '/studio': typeof StudioIndexRoute
  '/studio/brief/$briefId': typeof StudioBriefBriefIdRoute
  '/studio/campaigns/$campaignId': typeof StudioCampaignsCampaignIdRoute
  '/studio/brief': typeof StudioBriefIndexRoute
  '/studio/campaigns': typeof StudioCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/studio': typeof StudioRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/studio/$threadId': typeof StudioThreadIdRoute
  '/studio/business': typeof StudioBusinessRoute
  '/studio/conversations': typeof StudioConversationsRoute
  '/studio/followups': typeof StudioFollowupsRoute
  '/studio/lists': typeof StudioListsRoute
  '/studio/offers': typeof StudioOffersRoute
  '/studio/path': typeof StudioPathRoute
  '/studio/todos': typeof StudioTodosRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/brief/$briefId': typeof StudioBriefBriefIdRoute
  '/studio/campaigns/$campaignId': typeof StudioCampaignsCampaignIdRoute
  '/studio/brief/': typeof StudioBriefIndexRoute
  '/studio/campaigns/': typeof StudioCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/studio'
    | '/api/chat'
    | '/studio/$threadId'
    | '/studio/business'
    | '/studio/conversations'
    | '/studio/followups'
    | '/studio/lists'
    | '/studio/offers'
    | '/studio/path'
    | '/studio/todos'
    | '/studio/'
    | '/studio/brief/$briefId'
    | '/studio/campaigns/$campaignId'
    | '/studio/brief/'
    | '/studio/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/studio/$threadId'
    | '/studio/business'
    | '/studio/conversations'
    | '/studio/followups'
    | '/studio/lists'
    | '/studio/offers'
    | '/studio/path'
    | '/studio/todos'
    | '/studio'
    | '/studio/brief/$briefId'
    | '/studio/campaigns/$campaignId'
    | '/studio/brief'
    | '/studio/campaigns'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/studio'
    | '/api/chat'
    | '/studio/$threadId'
    | '/studio/business'
    | '/studio/conversations'
    | '/studio/followups'
    | '/studio/lists'
    | '/studio/offers'
    | '/studio/path'
    | '/studio/todos'
    | '/studio/'
    | '/studio/brief/$briefId'
    | '/studio/campaigns/$campaignId'
    | '/studio/brief/'
    | '/studio/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  StudioRoute: typeof StudioRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$threadId': {
      id: '/studio/$threadId'
      path: '/$threadId'
      fullPath: '/studio/$threadId'
      preLoaderRoute: typeof StudioThreadIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/business': {
      id: '/studio/business'
      path: '/business'
      fullPath: '/studio/business'
      preLoaderRoute: typeof StudioBusinessRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/conversations': {
      id: '/studio/conversations'
      path: '/conversations'
      fullPath: '/studio/conversations'
      preLoaderRoute: typeof StudioConversationsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/followups': {
      id: '/studio/followups'
      path: '/followups'
      fullPath: '/studio/followups'
      preLoaderRoute: typeof StudioFollowupsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/lists': {
      id: '/studio/lists'
      path: '/lists'
      fullPath: '/studio/lists'
      preLoaderRoute: typeof StudioListsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/offers': {
      id: '/studio/offers'
      path: '/offers'
      fullPath: '/studio/offers'
      preLoaderRoute: typeof StudioOffersRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/path': {
      id: '/studio/path'
      path: '/path'
      fullPath: '/studio/path'
      preLoaderRoute: typeof StudioPathRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/todos': {
      id: '/studio/todos'
      path: '/todos'
      fullPath: '/studio/todos'
      preLoaderRoute: typeof StudioTodosRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/brief/': {
      id: '/studio/brief/'
      path: '/brief'
      fullPath: '/studio/brief/'
      preLoaderRoute: typeof StudioBriefIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/brief/$briefId': {
      id: '/studio/brief/$briefId'
      path: '/brief/$briefId'
      fullPath: '/studio/brief/$briefId'
      preLoaderRoute: typeof StudioBriefBriefIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/campaigns/': {
      id: '/studio/campaigns/'
      path: '/campaigns'
      fullPath: '/studio/campaigns/'
      preLoaderRoute: typeof StudioCampaignsIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/campaigns/$campaignId': {
      id: '/studio/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/studio/campaigns/$campaignId'
      preLoaderRoute: typeof StudioCampaignsCampaignIdRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface StudioRouteChildren {
  StudioThreadIdRoute: typeof StudioThreadIdRoute
  StudioBusinessRoute: typeof StudioBusinessRoute
  StudioConversationsRoute: typeof StudioConversationsRoute
  StudioFollowupsRoute: typeof StudioFollowupsRoute
  StudioListsRoute: typeof StudioListsRoute
  StudioOffersRoute: typeof StudioOffersRoute
  StudioPathRoute: typeof StudioPathRoute
  StudioTodosRoute: typeof StudioTodosRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioBriefBriefIdRoute: typeof StudioBriefBriefIdRoute
  StudioCampaignsCampaignIdRoute: typeof StudioCampaignsCampaignIdRoute
  StudioBriefIndexRoute: typeof StudioBriefIndexRoute
  StudioCampaignsIndexRoute: typeof StudioCampaignsIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioThreadIdRoute: StudioThreadIdRoute,
  StudioBusinessRoute: StudioBusinessRoute,
  StudioConversationsRoute: StudioConversationsRoute,
  StudioFollowupsRoute: StudioFollowupsRoute,
  StudioListsRoute: StudioListsRoute,
  StudioOffersRoute: StudioOffersRoute,
  StudioPathRoute: StudioPathRoute,
  StudioTodosRoute: StudioTodosRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioBriefBriefIdRoute: StudioBriefBriefIdRoute,
  StudioCampaignsCampaignIdRoute: StudioCampaignsCampaignIdRoute,
  StudioBriefIndexRoute: StudioBriefIndexRoute,
  StudioCampaignsIndexRoute: StudioCampaignsIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  StudioRoute: StudioRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
