/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioThreadIdRouteImport } from './routes/studio.$threadId'
import { Route as StudioListsRouteImport } from './routes/studio.lists'
import { Route as StudioPathRouteImport } from './routes/studio.path'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioThreadIdRoute = StudioThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => StudioRoute,
} as any)
const StudioListsRoute = StudioListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPathRoute = StudioPathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/studio': typeof StudioRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/studio/$threadId': typeof StudioThreadIdRoute
  '/studio/lists': typeof StudioListsRoute
  '/studio/path': typeof StudioPathRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/studio/$threadId': typeof StudioThreadIdRoute
  '/studio/lists': typeof StudioListsRoute
  '/studio/path': typeof StudioPathRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/studio': typeof StudioRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/studio/$threadId': typeof StudioThreadIdRoute
  '/studio/lists': typeof StudioListsRoute
  '/studio/path': typeof StudioPathRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/studio'
    | '/api/chat'
    | '/studio/$threadId'
    | '/studio/lists'
    | '/studio/path'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/studio/$threadId'
    | '/studio/lists'
    | '/studio/path'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/studio'
    | '/api/chat'
    | '/studio/$threadId'
    | '/studio/lists'
    | '/studio/path'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  StudioRoute: typeof StudioRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$threadId': {
      id: '/studio/$threadId'
      path: '/$threadId'
      fullPath: '/studio/$threadId'
      preLoaderRoute: typeof StudioThreadIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/lists': {
      id: '/studio/lists'
      path: '/lists'
      fullPath: '/studio/lists'
      preLoaderRoute: typeof StudioListsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/path': {
      id: '/studio/path'
      path: '/path'
      fullPath: '/studio/path'
      preLoaderRoute: typeof StudioPathRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface StudioRouteChildren {
  StudioThreadIdRoute: typeof StudioThreadIdRoute
  StudioListsRoute: typeof StudioListsRoute
  StudioPathRoute: typeof StudioPathRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioThreadIdRoute: StudioThreadIdRoute,
  StudioListsRoute: StudioListsRoute,
  StudioPathRoute: StudioPathRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  StudioRoute: StudioRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
